package gg.bot.bottg.condition;

public enum Conditions {
    START,
    CHOOSE_STREAK_OR_INFO,
    SELECTED_STREAK_AND_WAIT_GIZMO_LOGIN,
    SELECTED_STREAK_AND_WAIT_GIZMO_PASS,
    AGAIN_ENTER_LOGIN_PASSWORD,
    CHOOSE_PRIZE,
    USER_IS_EXIST,
    SUBMIT_STREAK_DAY,
    INFO_ABOUT_STREAK_AWARDS,
    SELECTED_INFO,
    SELECTED_INFO_ABOUT_STREAK_SYSTEM,
    DELETE_SELECT,
    DELETE_AGREE,
    DELETE_DECLINE
}
