package gg.bot.bottg.enums;

public enum Conditions {
    START,
    CHOOSE_STREAK_OR_INFO,
    CHOOSE_NO,
    SELECTED_STREAK_AND_WAIT_GIZMO_LOGIN,
    SELECTED_STREAK_AND_WAIT_GIZMO_PASS,
    AGAIN_ENTER_LOGIN_PASSWORD,
    CHOOSE_PRIZE,
    USER_IS_EXIST,
    SUBMIT_STREAK_DAY,
    INFO_ABOUT_STREAK_AWARDS,
    SELECTED_INFO,
    SELECTED_INFO_ABOUT_STREAK_SYSTEM,
    DELETE_SELECT,
    DELETE_AGREE,
    DELETE_DECLINE,
    RECPASS_ENTER_PHONE_NUMBER,
    RECPASS_ENTER_FOUR_NUMBER_CODE,
    RECPASS_ENTER_NEW_PASS,
    RECPASS_ENTER_AGAIN_CONFIRM_CODE_OR_SEND_NEW_CONFIRM_CODE,

    PROMO_START_ENTER;

}
